### ISSUE TITLE
 CHEAT_010 Edit sent messages

### ISSUE THREAD

**Issue by Hiebl** [sw19-tug/morning10#10]
Acceptance Criteria:
-) the message entries which have been sent already to the cheating partner’s device must be editable and hence open an edit field if long pressed on them
-) the sent messages (records in the history list) are editable
-) changed messages are re-sent and changed in the cheating partner’s history list accordingly

Description: 
As a user I want to be able to change and edit my already sent messages and these edited messages must be updated on the partner’s device as well.

**Comment by dwildr** [comment]
done
