### ISSUE TITLE
CHEAT_011 Edit sent message indicator and Date/Timestamp

### ISSUE THREAD

**Issue by Hiebl** [sw19-tug/morning10#11]
Acceptance Criteria: 
-) when a message was edited no matter by whom (cheating partner or me) a non-editable edit-timestamp shall indicate the change of the record.
-) the edit timestamp is updated on the connected cheating partner’s device as well and hence is visible there also.

Description: 
As a user I want to know when a message was changed by whom and therefore want a Date/Timestamp as an indicator for every changed message.

**Comment by dwildr** [comment]
done in commit 8839d39a239b955c83cd5d1839ce6d75f6806220
