### ISSUE TITLE
CHEAT_004 Text entry field

### ISSUE THREAD

**Issue by Hiebl** [sw19-tug/morning10#4]
Acceptance Criteria:
-) there must be an editable text field
-) horizontal width of the text field fits the screen width
-) vertical width of the text field is dynamically increased depending on the number of lines of text entered in this field.

Description: 
As a user I want to enter the text to be sent to the connected cheating partner into an editable text field.

**Comment by matzeschmo** [comment]
text entry field has all mandatory features 👍
